name: socialv
description: A new Flutter project.
publish_to: 'none'

version: 6.12.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Common packages
  nb_utils: ^6.0.6
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  flutter_spinkit: ^5.2.0
  lottie: ^2.7.0

  # Media
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  just_audio: ^0.9.36
  syncfusion_flutter_pdfviewer: ^23.2.4
  photo_view: ^0.14.0
  appinio_video_player: ^1.2.2
  giphy_get: ^3.5.2
  video_player: ^2.8.1
  youtube_player_flutter: ^8.1.2
  visibility_detector: ^0.4.0+2

  # APIs
  http: ^1.1.0
  intl: ^0.18.1
  html: ^0.15.4

  flutter_html: ^3.0.0-beta.1
  flutter_html_table: ^3.0.0-beta.2
  google_mobile_ads: ^3.1.0

  # State Management Technique
  mobx: ^2.2.1
  flutter_mobx: ^2.2.0

  # Share
  share_plus: ^7.2.1
  flutter_custom_tabs: ^1.2.1

  # Firebase
  firebase_crashlytics: ^3.4.5
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1
  firebase_messaging: ^14.7.5
  cloud_firestore: ^4.13.2

  # AUTHENTICATION
  google_sign_in: ^6.1.6
  the_apple_sign_in: ^1.1.1

  # Remote Notification
  onesignal_flutter: ^5.0.4

  # Story
  story_time: ^1.0.6
  numberpicker: ^2.1.2

  # Others
  flutter_emoji: ^2.5.1
  flutter_mentions: ^2.0.1
  flutter_portal: ^0.4.0
  linear_timer: ^2.0.0
  country_picker: ^2.0.22
  any_link_preview: ^3.0.1
  string_contains: ^2.3.0
  carousel_slider: ^4.2.1

  #Payment
  flutter_stripe: ^9.4.0
  razorpay_flutter: 1.3.5

  # Agora
  agora_rtc_engine: ^5.2.0
  permission_handler: ^10.2.0

  flutter_localizations:
    sdk: flutter
  go_router: ^12.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/flag/
    - assets/icons/
    - assets/lottie/


